#!/usr/bin/env bash
#Configures a new Ubuntu machie to install nginx
#Serves a page that would return a Hello World! string

echo -e "Updating and installing Nginx.\n"

sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

#Starting nginx service
sudo service nginx start

#Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

#Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.htmml.bckp

#Restarting nginx
sudo service nginx restart

echo -e "\nCompleted. ✅\n"
