#!/usr/bin/env bash
# Install the ufw firewall and 
#    setup a few rules on web-01
# Configures a ufw firewall to block all incoming traffic
# except for TCP ports:
#            22 (SSH),
#            443 (HTTPS SSL),
#            80 (HTTP)

echo -e "Updating\n"

sudo apt-get update

echo -e "Installing UFW\n"

sudo apt-get install -y ufw

echo -e "Configuring ufw\n"

#Deny Incoming and Allow Outgoing

sudo ufw default deny incoming
sudo ufw default allow outgoing

#Allow ports

sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443

#Enable firewall

sudo ufw enable

echo -e "Completed the Process\n"
