#!/usr/bin/env bash
#  Bash script that creates an RSA key pair.
# name of the created private key is school
#number of bits in the created key are 4096
#The created key must be protected by the passphrase betty

ssh-keygen -b 4096 -f school -N betty
